export default function FAQ(){
    const faqContent    =   [
        {question: "Gürün ile Malatya iline bağlı Darende merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Darende merkez arasında 36 kilometre mesafe vardır. Aracınız ile yaklasık 30 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-darende-arasi-kilometre.png"},
        {question: "Gürün ile Malatya arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Malatya merkez arasında 155 kilometre mesafe vardır. Aracınız ile yaklasık 2 saat içerisinde ulaşabilirsiniz.", direction: "/gurun-malatya-merkez-arasi.jpg"},
        {question: "Gürün ile Malatya iline bağlı Yeşilyurt merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Yeşilyurt merkez arasında 139 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 50 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-yesilyurt-arasi-mesafe.png"},
        {question: "Gürün ile Kahramanmaraş iline bağlı Elbistan merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Elbistan merkez arasında 80 kilometre mesafe vardır. Aracınız ile -adeta cenneten bir köşe olan- Gökpınar Gölü'ne giden yol üzerinden yaklasık 1 saat 15 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-elbistan-arasi-mesafe-1.png"},
        {question: "Gürün ile Malatya iline bağlı Hekimhan merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Hekimhan merkez arasında 85 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 25 dakika içerisinde ulaşabilirsiniz. Fakat Hekimhan'a Sivas yolu üzerinden gitmek isterseniz Eskibektaşlı köyü yolunu kullanarak da ulaşabilirsiniz. Son güzergahta yolculuğunuz 30 dakika uzayacaktır, bilginize.", direction: "/gurun-malatya-merkez-arasi.png"},
        {question: "Gürün ile Kangal merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Kangal merkez arasında 75 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat içerisinde ulaşabilirsiniz.", direction: "/gurun-kangal-arasi-mesafe.png"},
        {question: "Gürün ile Divriği merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Divriği merkez arasında 158 kilometre mesafe vardır. Aracınız ile yaklasık 2 saat içerisinde ulaşabilirsiniz.", direction: "/gurun-divrigi-arasi-mesafe.png"},
        {question: "Gürün ile Ulaş merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Ulaş merkez arasında 98 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 10 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-ulas-arasi-mesafe.png"},
        {question: "Gürün ile Gemerek merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Gemerek merkez arasında 156 kilometre mesafe vardır. Aracınız ile yaklasık 2 saat 15 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-gemerek-arasi-mesafe.png"},
        {question: "Gürün ile Sivas merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Sivas merkez arasında 136 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 45 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-sivas-merkez-arasi.png"},
        {question: "Gürün ile Şarkışla merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Şarkışla merkez arasında en kısa mesafe 140 kilometre mesafedir ve 1 saat 45 dakika içerisinde ulaşabilirsiniz. Fakat Şarkışla'ya Sivas yolu üzerinden giderseniz, 175 kilometrelik 2 saatlik yolculuk ile de bu noktaya ulaşabilirsiniz.", direction: "/gurun-sarkisla-arasi-mesafe.png"},
        {question: "Gürün ile Kayseri iline bağlı Pınarbaşı merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Pınarbaşı merkez arasında 102 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 10 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-pinarbasi-arasi-mesafe.png"},
        {question: "Gürün ile Kayseri iline bağlı Sarız merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Sarız merkez arasında 90 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 30 dakika içerisinde ulaşabilirsiniz. Fakat Sarız'a Pınarbaşı'na uğrayarak gitmek isterseniz mesafeniz 144 kilometreye çıkıyor ve yolculuğunuz 1 saat 43 dakikaya çıkıyor.", direction: "/gurun-sariz-arasi-mesafe.png"},
        {question: "Gürün ile Kayseri iline bağlı Sarıoğlan merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Sarıoğlan merkez arasında 165 kilometre mesafe vardır. Aracınız ile yaklasık 2 saat 15 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-sarioglan-arasi-mesafe.png"},
        {question: "Gürün ile Kayseri iline bağlı Bünyan merkez arası kaç kilometre mesafe vardır?", answer: "Gürün merkez ile Bünyan merkez arasında 165 kilometre mesafe vardır. Aracınız ile yaklasık 1 saat 50 dakika içerisinde ulaşabilirsiniz.", direction: "/gurun-bunyan-arasi-mesafe.png"},
    ];
    return(
        <>
            {faqContent.map((faq, i) => <div className="p-2" key={i}><h2 className="text-xl font-bold">{faq.question}</h2><p className="tracking-wide mt-2 p-2 border-l-4 border-slate-500">{faq.answer}</p></div>)}
        </>
    )
}