export default function sitemap() {
    return [
      {
        url: 'https://sivasgurun.com',
        lastModified: new Date(),
        changeFrequency: 'hourly',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/iletisim',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/hakkimizda',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gizlilik-politikamiz',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/cerez-politikasi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/kvkk',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  /*
      {
        url: 'https://sivasgurun.com/haberler',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  */
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/gurun',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/telefon-rehberi/oto-cekici-kurtarma',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.6,
      },
	  {
        url: 'https://sivasgurun.com/telefon-rehberi/kaymakamlik-ve-birimleri',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.6,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/depremler/gurun',
        lastModified: new Date(),
        changeFrequency: 'hourly',
        priority: 0.6,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  /*
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-akdere-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-akpinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-ayvali-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-baglicay-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-bahceici-tihmin-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-basoren-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-beypinari-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-bogrudelik-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-bozhuyuk-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-camiliyurt-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-camlica-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-cicekyurt-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-davulhuyuk-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-dayakpinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-devecayiri-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-durmepinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-erdogan-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-eskibektasli-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-eskihamal-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-gobekoren-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-gokceyazi-otlukilise-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-guldede-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-gullubucak-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-gunes-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-huyukluyurt-hoyuklu-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-incesu-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kaledere-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-karadoruk-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-karahisar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-karakuyu-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-karaoren-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-karapinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kaskoy-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kavakkoy-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kayalar-saksakpinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kaynarca-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kilicdogan-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kindiralik-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kizilburun-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kiziloren-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kizilpinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-konakpinar-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-koyunlu-gellos-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kulahli-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-kurkcu-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-magara-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-mahkenli-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-osmandede-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-resadiye-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-sarica-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-sularbasi-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-tepecik-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yaylacik-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yazyurdu-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yelken-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yenibektasli-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yesildere-hamalcayi-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yilanhuyuk-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yolgecen-tekirahma-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/hava-durumu/koyler/gurun/gurun-yuva-koyu-hava-durumu',
        lastModified: new Date(),
        changeFrequency: 'daily',
        priority: 1,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yuva-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yolgecen-tekirahma-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yilanhuyuk-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yesildere-hamalcayi-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yenibektasli-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yelken-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yazyurdu-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-yaylacik-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-tepecik-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-sularbasi-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-sarica-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-resadiye-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-osmandede-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-mahkenli-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-magara-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kurkcu-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kulahli-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-koyunlu-gellos-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-konakpinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kizilpinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kiziloren-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kizilburun-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kindiralik-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kilicdogan-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kaynarca-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kayalar-saksakpinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kavakkoy-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kaskoy-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-karapinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-karaoren-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-karakuyu-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-karahisar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-karadoruk-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-kaledere-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-incesu-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-huyukluyurt-hoyuklu-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-gunes-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-gullubucak-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-guldede-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-gokceyazi-otlukilise-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-gobekoren-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-eskihamal-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-eskibektasli-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-erdogan-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-durmepinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-devecayiri-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-dayakpinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-davulhuyuk-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	   {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-beypinari-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-cicekyurt-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-akdere-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-akpinar-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-ayvali-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-baglicay-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-bahceici-tihmin-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-basoren-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-bogrudelik-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-bozhuyuk-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-camiliyurt-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/koyler/gurun/gurun-camlica-koyu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	 
      {
        url: 'https://sivasgurun.com/haberler/gurundeki-afet-konutlari-projesinde-21-ilerleme-saglandi-9',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/haberler/sivasta-market-denetimleri-tuketici-sagligi-on-planda-7',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      */
      {
        url: 'https://sivasgurun.com/gezilecekyerler/gurun/sugul-vadisi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/gezilecekyerler/gurun/gokpinar-golu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-ataturk-kongre-binasi-ve-muzesi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-cumhuriyet-kent-meydani',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-kale-cami',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-kalesi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-sifaiye-medresesi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
	  {
        url: 'https://sivasgurun.com/gezilecekyerler/sivas/sivas-subasi-hani',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-ulu-cami',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-ermeni-kilisesi',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-sali',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-kaya-evleri',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-meydan-cami',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-toraman-cami',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-kapali-yuzme-havuzu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-kapali-spor-salonu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-cayboyu-dogal-yasam-parki',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-ilce-stadyumu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://sivasgurun.com/mekanlar/gurun/gurun-burcevi-mezar-aniti',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
    ]
}